apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open
  template:
    metadata:
      labels:
        app: open
    spec:
      containers:
        - name: open
          image: fahiz/auth
          env:
            - name: MONGO_URL
              value: "mongodb+srv://fahiz:fahiz123@cluster0.movezpo.mongodb.net"
---
apiVersion: v1
kind: Service
metadata:
  name: open-srv
spec:
  selector:
    app: open
  ports:
    - name: open
      protocol: TCP
      port: 3000
      targetPort: 3000
